{
  "id": 41349429,
  "name": "87",
  "full_name": "adamkrapish/87",
  "owner": {
    "login": "adamkrapish",
    "id": 13958142,
    "avatar_url": "https://avatars.githubusercontent.com/u/13958142?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/adamkrapish",
    "html_url": "https://github.com/adamkrapish",
    "followers_url": "https://api.github.com/users/adamkrapish/followers",
    "following_url": "https://api.github.com/users/adamkrapish/following{/other_user}",
    "gists_url": "https://api.github.com/users/adamkrapish/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/adamkrapish/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/adamkrapish/subscriptions",
    "organizations_url": "https://api.github.com/users/adamkrapish/orgs",
    "repos_url": "https://api.github.com/users/adamkrapish/repos",
    "events_url": "https://api.github.com/users/adamkrapish/events{/privacy}",
    "received_events_url": "https://api.github.com/users/adamkrapish/received_events",
    "type": "User",
    "site_admin": false
  },
  "private": false,
  "html_url": "https://github.com/adamkrapish/87",
  "description": null,
  "fork": false,
  "url": "https://api.github.com/repos/adamkrapish/87",
  "forks_url": "https://api.github.com/repos/adamkrapish/87/forks",
  "keys_url": "https://api.github.com/repos/adamkrapish/87/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/adamkrapish/87/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/adamkrapish/87/teams",
  "hooks_url": "https://api.github.com/repos/adamkrapish/87/hooks",
  "issue_events_url": "https://api.github.com/repos/adamkrapish/87/issues/events{/number}",
  "events_url": "https://api.github.com/repos/adamkrapish/87/events",
  "assignees_url": "https://api.github.com/repos/adamkrapish/87/assignees{/user}",
  "branches_url": "https://api.github.com/repos/adamkrapish/87/branches{/branch}",
  "tags_url": "https://api.github.com/repos/adamkrapish/87/tags",
  "blobs_url": "https://api.github.com/repos/adamkrapish/87/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/adamkrapish/87/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/adamkrapish/87/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/adamkrapish/87/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/adamkrapish/87/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/adamkrapish/87/languages",
  "stargazers_url": "https://api.github.com/repos/adamkrapish/87/stargazers",
  "contributors_url": "https://api.github.com/repos/adamkrapish/87/contributors",
  "subscribers_url": "https://api.github.com/repos/adamkrapish/87/subscribers",
  "subscription_url": "https://api.github.com/repos/adamkrapish/87/subscription",
  "commits_url": "https://api.github.com/repos/adamkrapish/87/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/adamkrapish/87/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/adamkrapish/87/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/adamkrapish/87/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/adamkrapish/87/contents/{+path}",
  "compare_url": "https://api.github.com/repos/adamkrapish/87/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/adamkrapish/87/merges",
  "archive_url": "https://api.github.com/repos/adamkrapish/87/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/adamkrapish/87/downloads",
  "issues_url": "https://api.github.com/repos/adamkrapish/87/issues{/number}",
  "pulls_url": "https://api.github.com/repos/adamkrapish/87/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/adamkrapish/87/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/adamkrapish/87/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/adamkrapish/87/labels{/name}",
  "releases_url": "https://api.github.com/repos/adamkrapish/87/releases{/id}",
  "created_at": "2015-08-25T07:22:57Z",
  "updated_at": "2015-08-25T07:22:57Z",
  "pushed_at": "2015-08-25T07:22:58Z",
  "git_url": "git://github.com/adamkrapish/87.git",
  "ssh_url": "git@github.com:adamkrapish/87.git",
  "clone_url": "https://github.com/adamkrapish/87.git",
  "svn_url": "https://github.com/adamkrapish/87",
  "homepage": null,
  "size": 0,
  "stargazers_count": 0,
  "watchers_count": 0,
  "language": null,
  "has_issues": true,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": false,
  "forks_count": 0,
  "mirror_url": null,
  "open_issues_count": 0,
  "forks": 0,
  "open_issues": 0,
  "watchers": 0,
  "default_branch": "master",
  "permissions": {
    "admin": true,
    "push": true,
    "pull": true
  },
  "network_count": 0,
  "subscribers_count": 1
}
Initialized empty Git repository in /home/devil31/Documents/87/.git/
[master (root-commit) 165fbb9] "87"
 8 files changed, 825 insertions(+)
 create mode 100644 about.cfm
 create mode 100644 blog.cfm
 create mode 100644 blogpost.cfm
 create mode 100644 contact.cfm
 create mode 100644 index.cfm
 create mode 100644 portfolio.cfm
 create mode 100644 resume.cfm
 create mode 100644 sorry.cfm
Branch master set up to track remote branch master from origin.
